package com.homlin.module;

public interface Constants {

	String SYSKEY = "C2682162-72BE-4FFB-A6B3-E3A17487C918"; // 系统KEY，加密
	// String SYSID = "4028808b3633632c0136336454e40001"; // 系统ID
	String CHARSET = "UTF-8"; // 系统编码
	String TRUE = "1"; // 数据库true标记
	String FALSE = "0"; // 数据库false标记

	// String TABLE_PREFIX = ""; // 表前缀

	// String TABLE_ADMIN = TABLE_PREFIX + "admin";

	// String SUPER_ADMIN_ID = "4028808b4420708e0144207095750000"; // 超级管理员ID

	// 管理员SESSION-KEY
	String SESSION_ADMIN = "SESSION_ADMIN";
	String SESSION_ADMIN_ID = "SESSION_ADMIN_ID";
	String SESSION_ADMIN_USERNAME = "SESSION_ADMIN_USERNAME";
	String SESSION_ADMIN_NAME = "SESSION_ADMIN_NAME";
	String SESSION_ADMIN_ISLOGIN = "SESSION_ADMIN_ISLOGIN";
	String SESSION_ADMIN_AUTHORITY = "SESSION_ADMIN_AUTHORITY";
	String SESSION_ADMIN_ISSUPER = "SESSION_ADMIN_ISSUPER";

	// 会员SESSION-KEY
	String SESSION_MEMBER = "SESSION_MEMBER";
	String SESSION_MEMBER_ID = "SESSION_MEMBER_ID";
	String SESSION_MEMBER_USERNAME = "SESSION_MEMBER_USERNAME";
	String SESSION_MEMBER_NAME = "SESSION_MEMBER_NAME";
	String SESSION_MEMBER_ISLOGIN = "SESSION_MEMBER_ISLOGIN";
	String SESSION_MEMBER_GRADE = "SESSION_MEMBER_GRADE";
	String SESSION_MEMBER_ISLOGINBYQQ = "SESSION_MEMBER_ISLOGINBYQQ";

	String RESPONSE_STATUSCODE = "STATUSCODE"; // RESPONSE HEADER
	String RESPONSE_STATUSCODE_UNAUTHORIZED = "UNAUTHORIZED"; // 没有权限！
	String RESPONSE_STATUSCODE_NEEDLOGIN = "NEEDLOGIN"; // 未登入或登入超时，请重新登入！

	String MESSAGE_PERMISSION_DENIED = "没有权限";

	String SESSION_ORDERINFO_TOKEN = "SESSION_ORDERINFO_TOKEN"; // 订单信息TOKEN，防止重复提交或多页面时订单明细变更

	// String COOKIE_CART_TOTALQUANTITY = "CART_TOTALQUANTITY";

}
